helm:
  parameters:
  - name: image.repository
    value: 836759839628.dkr.ecr.ap-south-1.amazonaws.com/jenkins/dockerimage
    forcestring: false
  - name: image.tag
    value: "30"
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 836759839628.dkr.ecr.ap-south-1.amazonaws.com/jenkins/dockerimage
    forcestring: true
