replicaCount: 2

image:
  repository: 836759839628.dkr.ecr.ap-south-1.amazonaws.com/jenkins/dockerimage
  tag: "21"
  pullPolicy: IfNotPresent

#imagePullSecrets: ecr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  scheme: internet-facing
  targetType: ip
  host: john.jonathanjo.great-site.net
